### PR TITLE
[fix] correct scaling

### LINKED ISSUE #13: A few potential fixes
Thanks for this Image uploader/resizer. I've been adapting it for another purpose (just the resizing part), and noticed a few things weren't working in my own testing. It looks like all are simple fixes, and just wanted to pass them along:

- As far as I can tell, the client-side resizing does not come into play at all unless the `config.autoRotate` option is `true`. See [this conditional](https://github.com/rossturner/HTML5-ImageUploader/blob/master/src/main/webapp/js/ImageUploader.js#L63). I basically just removed the autoRotate conditional and left everything within it, and it seems to work fine.  

- The `config.maxSize` option doesn't appear to work as described in the README. It suggests that it is expecting a float like 1.7, but the actual code seems to be expecting something different. I was able to correct it by adjusting the maxSize part of the `scaleImage` function to the following (though I'm guessing you know something better):
~~~~~
if(this.config.maxSize > 0 && (this.config.maxSize < (canvas.width * canvas.height) / 1000000)) { 
  var mSize = Math.floor(Math.sqrt(this.config.maxSize * ratio) * 1000);
  mWidth = mWidth > 0 ? Math.min(mWidth, mSize) : mSize;
}
~~~~~
- As far as I can tell, your resizing code works equally well with png and gif files (?), once I replaced the static `image/jpeg` content-type from the `canvas.toDataURL()` call with `this.currentFile.type` at the bottom of the `scaleImage` function. I changed it to this below, and it appears to be working, though I may be missing something. 
~~~~~
var quality = this.currentFile.type == 'image/jpeg' ? this.config.quality : 1.0;
var imageData = canvas.toDataURL(this.currentFile.type, quality);
~~~~~

### PR DESCRIPTION
**Pull request by rvalitov**
Fixes #13
I added code to fix all the problems from there, except the last line about exporting in function `toDataURL` to formats other than `jpeg`. There are 2 reasons for that:

- it's not a bug, but a feature
- not all browsers may support export to formats other than `jpeg` and `png`. For example, Chrome even supports `webp`, see the [docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL).
- the user (programmer) may not want to have an image in the original format. Usually when we upload an image we want to have it in a predefined format, usually `jpeg`. It does not matter what kind of image the user selects: it may be any format supported by the browser, but after uploading we will have always `jpeg`, i.e. auto conversion is performed. I think it's logical. Alternatively, we could add a new option that would define the output format in which the JS code saves the final image. But such option is beyond the current PR.

### CODE REVIEW

File: src/main/webapp/js/ImageUploader.js [hunk 1]
```diff
@@ -77,6 +77,10 @@ ImageUploader.prototype.handleFileSelection = function(file, completionCallback)
 					This.scaleImage(img, completionCallback);
 				}
 			}
+			else{
+			    //No rotation, just scale the image
+                This.scaleImage(img, completionCallback);
+            }
```
Comment (rossturner) [inline src/main/webapp/js/ImageUploader.js:83]: The whitespacing here needs correcting
